#!/usr/bin/env node
'use strict';

/**
 * The Memory Conservatory — gallery page generator.
 *
 * Writes the gallery pages from `src/data/gallery.json`, which lists every
 * wedding and every photograph in it. One index page plus one page per wedding:
 *
 *   src/pages/gallery/index.html            ->  /gallery
 *   src/pages/gallery/<slug>.html           ->  /gallery/<slug>
 *
 * These are GENERATED. Edit the data file or this template, never the output —
 * the next build overwrites it. They are written into src/pages/ rather than
 * straight to public/ so that build.js expands their @includes exactly as it
 * does for a hand-written page: one rendering path, so the header and footer
 * can never drift between the gallery and the rest of the site.
 *
 * The photographs themselves live on Cloudflare Pages, not in this repo. Two
 * sizes are published: `thumb` (600px) for the grids and `full` (2560px) for
 * the lightbox. `baseUrl` in the data file is the only place that address
 * appears, so moving hosts is a one-line change.
 */

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const DATA = path.join(ROOT, 'src', 'data', 'gallery.json');
const OUT_DIR = path.join(ROOT, 'src', 'pages', 'gallery');

const GENERATED_NOTE =
  '<!-- GENERATED by gallery.js from src/data/gallery.json — do not edit by hand. -->';

/** Escape for use in an HTML attribute or text node. */
function esc(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/** "Sheena & Daniel" -> "Sheena and Daniel", for prose and alt text. */
function spoken(title) {
  return title.replace(/\s*&(amp;)?\s*/i, ' and ');
}

function thumb(base, slug, file) { return `${base}/${slug}/thumb/${file}`; }
function full(base, slug, file) { return `${base}/${slug}/full/${file}`; }

/* -----------------------------------------------------------------------------
   THE LIGHTBOX

   One <dialog> per page, filled by main.js from whichever thumbnail was
   clicked — so the 2560px sources appear once in the markup (on the buttons)
   rather than a second time here.

   Native <dialog> + showModal() gives the focus trap, the inert background,
   Esc-to-close and focus return for free. A hand-rolled overlay gets at least
   one of those wrong.
   -------------------------------------------------------------------------- */
function lightbox() {
  return `      <dialog class="lightbox" data-lightbox aria-label="Photograph">
        <button class="lightbox__close" type="button" data-lightbox-close aria-label="Close">
          <svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.4" aria-hidden="true">
            <path d="M3 3l10 10M13 3L3 13" stroke-linecap="round"/>
          </svg>
        </button>
        <img class="lightbox__img" data-lightbox-img alt="">
      </dialog>`;
}

/* -----------------------------------------------------------------------------
   INDEX — /gallery
   -------------------------------------------------------------------------- */
function indexPage(data) {
  const { baseUrl, weddings } = data;
  const total = weddings.reduce((n, w) => n + w.photos.length, 0);
  const lead = weddings[0];

  const cards = weddings.map((w, i) => `        <a class="gallery-card reveal" href="/gallery/${w.slug}"${
    i ? ` style="--reveal-delay:${i * 80}ms"` : ''}>
          <span class="gallery-card__frame">
            <img src="${thumb(baseUrl, w.slug, w.cover)}"
                 alt="${esc(spoken(w.title))} on their wedding day"
                 loading="${i < 2 ? 'eager' : 'lazy'}" decoding="async"
                 sizes="(max-width: 48rem) 100vw, (max-width: 68rem) 50vw, 33vw">
            <span class="gallery-card__veil" aria-hidden="true"></span>
          </span>
          <span class="gallery-card__body">
            <span class="gallery-card__title">${esc(w.title)}</span>
            <span class="gallery-card__meta">${esc(w.genre)} &middot; ${w.photos.length} photographs</span>
          </span>
        </a>`).join('\n\n');

  return `<!doctype html>
<html lang="en">
${GENERATED_NOTE}
<head>
  <!-- @include head title="Gallery" description="Weddings photographed by The Memory Conservatory across Chennai, Tamil Nadu and beyond — ${total} photographs from ${weddings.length} celebrations." -->

  <noscript>
    <style>.reveal { opacity: 1 !important; transform: none !important; }</style>
  </noscript>
</head>

<body>

  <!-- @include header active="gallery" -->

  <main id="main">

    <section class="page-hero" aria-label="Gallery">
      <img class="page-hero__img" src="${full(baseUrl, lead.slug, lead.cover)}"
           alt="" style="--focal:50% 45%" fetchpriority="high" decoding="async">

      <div class="page-hero__scrim" aria-hidden="true"></div>
      <div class="hero__grain" aria-hidden="true"></div>

      <div class="shell page-hero__inner">
        <p class="eyebrow eyebrow--ruled">Gallery</p>
        <h1 class="page-hero__title">Weddings we have <em>photographed</em></h1>
      </div>
    </section>


    <section class="section section--white">
      <div class="shell">
        <div class="reveal" style="max-width:var(--container-prose)">
          <p class="eyebrow eyebrow--ruled">The Collections</p>
          <h2 class="section__title">Every celebration, <em>in full</em></h2>
        </div>
      </div>

      <div class="shell">
        <div class="gallery-grid">
${cards}
        </div>
      </div>
    </section>

    <!-- @include testimonials -->

  </main>

  <!-- @include footer -->

  <script type="module" src="/assets/js/main.js"></script>
</body>
</html>
`;
}

/* -----------------------------------------------------------------------------
   ONE WEDDING — /gallery/<slug>
   -------------------------------------------------------------------------- */
function weddingPage(data, wedding, position) {
  const { baseUrl, weddings } = data;
  const { slug, title, cover, photos } = wedding;
  const name = spoken(title);
  const next = weddings[(position + 1) % weddings.length];

  const tiles = photos.map((p, i) => `          <figure class="shot" style="--ratio:${p.ratio}">
            <button class="shot__open" type="button"
                    data-full="${full(baseUrl, slug, p.file)}"
                    aria-label="Open photograph ${i + 1} of ${photos.length} full size">
              <img src="${thumb(baseUrl, slug, p.file)}"
                   alt="${esc(name)} — photograph ${i + 1}"
                   loading="${i < 8 ? 'eager' : 'lazy'}" decoding="async"
                   sizes="(max-width: 36rem) 50vw, (max-width: 62rem) 33vw, 25vw">
            </button>
          </figure>`).join('\n');

  return `<!doctype html>
<html lang="en">
${GENERATED_NOTE}
<head>
  <!-- @include head title="${esc(title)}" description="Wedding photographs of ${esc(name)} by The Memory Conservatory — ${photos.length} images from their celebration." -->

  <noscript>
    <style>.reveal { opacity: 1 !important; transform: none !important; }</style>
  </noscript>
</head>

<body>

  <!-- @include header active="gallery" -->

  <main id="main">

    <section class="page-hero page-hero--short" aria-label="${esc(title)}">
      <img class="page-hero__img" src="${full(baseUrl, slug, cover)}"
           alt="" style="--focal:50% 40%" fetchpriority="high" decoding="async">

      <div class="page-hero__scrim" aria-hidden="true"></div>
      <div class="hero__grain" aria-hidden="true"></div>

      <div class="shell page-hero__inner">
        <p class="eyebrow eyebrow--ruled">
          <a class="page-hero__back" href="/gallery">Gallery</a>
        </p>
        <h1 class="page-hero__title">${esc(title)}</h1>
        <p class="page-hero__genre">${esc(wedding.genre)}</p>
      </div>
    </section>


    <section class="section section--white section--tight">
      <div class="shell">
        <div class="shot-grid">
${tiles}
        </div>

${lightbox()}

        <p class="gallery-next reveal">
          <a class="btn btn-outline" href="/gallery/${next.slug}">Next wedding: ${esc(next.title)}</a>
        </p>
      </div>
    </section>

    <!-- @include testimonials -->

  </main>

  <!-- @include footer -->

  <script type="module" src="/assets/js/main.js"></script>
</body>
</html>
`;
}

/* -------------------------------------------------------------------------- */

function build() {
  const started = Date.now();
  const data = JSON.parse(fs.readFileSync(DATA, 'utf8'));

  // Generated output only — safe to clear, and it drops pages for weddings
  // that have been removed from the data file.
  fs.rmSync(OUT_DIR, { recursive: true, force: true });
  fs.mkdirSync(OUT_DIR, { recursive: true });

  fs.writeFileSync(path.join(OUT_DIR, 'index.html'), indexPage(data), 'utf8');
  data.weddings.forEach((w, i) => {
    fs.writeFileSync(path.join(OUT_DIR, `${w.slug}.html`), weddingPage(data, w, i), 'utf8');
  });

  const photos = data.weddings.reduce((n, w) => n + w.photos.length, 0);
  console.log(
    `  gallery  ${data.weddings.length + 1} page(s), ${photos} photographs in ${Date.now() - started}ms`
  );
}

build();
